# Generated by Django 4.0.5 on 2022-06-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.TextField(default='what is the intro', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='what is the slug', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='write the author name', max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='provide the dessc', max_length=6000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='write the title', max_length=100),
        ),
    ]
