# Generated by Django 4.0.5 on 2022-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_introduction_blog_slug_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='tech', max_length=30),
        ),
    ]
