# Generated by Django 4.0.5 on 2022-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='provide the dessc', max_length=7000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='introduction',
            field=models.TextField(default='what is the intro', max_length=1000),
        ),
    ]
